(define (problem libros)
(:domain libros)
(:objects m1 m2 m3 m4 m5 m6 m6 m7 m8 m9 m10 m11 m12 - Mes
ac_nulla odio_cras magna_at_nunc quisque_erat_eros curabitur_in_libero erat ut et maecenas_ut integer consequat quis tincidunt_eu_felis nulla vitae_consectetuer diam_vitae mi_pede elementum tortor interdum turpis_eget lectus_vestibulum_quam sollicitudin est_lacinia_nisi congue_etiam vel_ipsum lectus_in lacinia vivamus_in_felis in_tempor_turpis justo_in etiam_justo ultrices_posuere venenatis diam bibendum nullam_molestie phasellus_id_sapien ut_blandit nunc_viverra_dapibus duis_ac nonummy_integer_non amet duis cubilia non_mi_integer nisl_ut penatibus ac_leo dictumst lacus quis_turpis_eget lobortis_est imperdiet_sapien_urna ipsum proin_interdum_mauris viverra_eget_congue maecenas est nisi_volutpat_eleifend iaculis_diam_erat_1 iaculis_diam_erat_2 ultrices_1 ultrices_2 ultrices_3 ultrices_4 ultrices_5 tortor_1 tortor_2 iaculis_justo_in_1 iaculis_justo_in_2 iaculis_justo_in_3 iaculis_justo_in_4 iaculis_justo_in_5 nisi_at_1 nisi_at_2 nisi_at_3 nisi_at_4 nisi_at_5 nisi_at_6 nisi_at_7 varius_1 varius_2 varius_3 varius_4 diam_1 diam_2 diam_3 diam_4 diam_5 diam_6 diam_7 nullam_1 nullam_2 nullam_3 purus_phasellus_1 purus_phasellus_2 eros_viverra_1 eros_viverra_2 eros_viverra_3 eros_viverra_4 eros_viverra_5 eros_viverra_6 eros_viverra_7 - Libro
)
(:init
(predecesor iaculis_diam_erat_1 iaculis_diam_erat_2)
(predecesor ultrices_1 ultrices_2)
(predecesor ultrices_2 ultrices_3)
(predecesor ultrices_3 ultrices_4)
(predecesor ultrices_4 ultrices_5)
(predecesor tortor_1 tortor_2)
(predecesor iaculis_justo_in_1 iaculis_justo_in_2)
(predecesor iaculis_justo_in_2 iaculis_justo_in_3)
(predecesor iaculis_justo_in_3 iaculis_justo_in_4)
(predecesor iaculis_justo_in_4 iaculis_justo_in_5)
(predecesor nisi_at_1 nisi_at_2)
(predecesor nisi_at_2 nisi_at_3)
(predecesor nisi_at_3 nisi_at_4)
(predecesor nisi_at_4 nisi_at_5)
(predecesor nisi_at_5 nisi_at_6)
(predecesor nisi_at_6 nisi_at_7)
(predecesor varius_1 varius_2)
(predecesor varius_2 varius_3)
(predecesor varius_3 varius_4)
(predecesor diam_1 diam_2)
(predecesor diam_2 diam_3)
(predecesor diam_3 diam_4)
(predecesor diam_4 diam_5)
(predecesor diam_5 diam_6)
(predecesor diam_6 diam_7)
(predecesor nullam_1 nullam_2)
(predecesor nullam_2 nullam_3)
(predecesor purus_phasellus_1 purus_phasellus_2)
(predecesor eros_viverra_1 eros_viverra_2)
(predecesor eros_viverra_2 eros_viverra_3)
(predecesor eros_viverra_3 eros_viverra_4)
(predecesor eros_viverra_4 eros_viverra_5)
(predecesor eros_viverra_5 eros_viverra_6)
(predecesor eros_viverra_6 eros_viverra_7)
(libro_leido lacus)
(libro_leido nonummy_integer_non)
(libro_leido diam_vitae)
(libro_leido curabitur_in_libero)
(libro_leido tincidunt_eu_felis)
(libro_leido mi_pede)
(libro_leido et)
(libro_leido turpis_eget)
(libro_leido ut_blandit)
(libro_leido diam)
(libro_leido quis)
(libro_leido justo_in)
(libro_leido nisi_volutpat_eleifend)
(libro_leido congue_etiam)
(libro_leido in_tempor_turpis)
(libro_leido lectus_vestibulum_quam)
(libro_leido bibendum)
(libro_leido est)
(libro_leido lobortis_est)
(libro_leido maecenas)
(libro_leido ut)
(libro_leido maecenas_ut)
(libro_leido sollicitudin)
(libro_leido lacinia)
(libro_leido ac_nulla)
(libro_a_leer varius_1)
(libro_a_leer magna_at_nunc)
(libro_a_leer diam_1)
(libro_a_leer diam_2)
(libro_a_leer diam_3)
(libro_a_leer diam_4)
(libro_a_leer diam_5)
(libro_a_leer diam_6)
(libro_a_leer duis)
(libro_a_leer tortor_1)
(libro_a_leer lectus_in)
(libro_a_leer eros_viverra_5)
(libro_a_leer phasellus_id_sapien)
(libro_a_leer iaculis_justo_in_3)
(libro_a_leer viverra_eget_congue)
(libro_a_leer iaculis_justo_in_5)
(libro_a_leer quisque_erat_eros)
(libro_a_leer est_lacinia_nisi)
(libro_a_leer iaculis_diam_erat_1)
(libro_a_leer quis_turpis_eget)
(libro_a_leer ultrices_posuere)
(libro_a_leer vitae_consectetuer)
(libro_a_leer nullam_1)
(libro_a_leer ac_leo)
(libro_a_leer nisi_at_4)
(libro_a_leer nisi_at_7)
(libro_a_leer nisi_at_6)
(libro_a_leer nisi_at_3)
(libro_a_leer nisi_at_2)
(libro_a_leer integer)
(libro_a_leer amet)
(libro_a_leer dictumst)
(libro_a_leer tortor)
(libro_a_leer ultrices_2)
(libro_a_leer nullam_molestie)
(libro_a_leer odio_cras)
(anterior m1 m2) (anterior m1 m3) (anterior m1 m4) (anterior m1 m5) (anterior m1 m6) (anterior m1 m7)
(anterior m1 m8) (anterior m1 m9) (anterior m1 m10) (anterior m1 m11) (anterior m1 m12)
(anterior m2 m3) (anterior m2 m4) (anterior m2 m5) (anterior m2 m6) (anterior m2 m7) (anterior m2 m8)
(anterior m2 m9) (anterior m2 m10) (anterior m2 m11) (anterior m2 m12)
(anterior m3 m4) (anterior m3 m5) (anterior m3 m6) (anterior m3 m7) (anterior m3 m8) (anterior m3 m9)
(anterior m3 m10) (anterior m3 m11) (anterior m3 m12)
(anterior m4 m5) (anterior m4 m6) (anterior m4 m7) (anterior m4 m8) (anterior m4 m9) (anterior m4 m10)
(anterior m4 m11) (anterior m4 m12) (anterior m5 m6) (anterior m5 m7) (anterior m5 m8) (anterior m5 m9) (anterior m5 m10) (anterior m5 m11)
(anterior m5 m12) (anterior m6 m7) (anterior m6 m8) (anterior m6 m9) (anterior m6 m10) (anterior m6 m11) (anterior m6 m12)
(anterior m7 m8) (anterior m7 m9) (anterior m7 m10) (anterior m7 m11) (anterior m7 m12) (anterior m8 m9) (anterior m8 m10) (anterior m8 m11) (anterior m8 m12)
(anterior m9 m10) (anterior m9 m11) (anterior m9 m12) (anterior m10 m11) (anterior m10 m12) (anterior m11 m12)
)
(:goal (forall (?l - Libro) (imply (libro_a_leer ?l) (libro_asignado ?l)))))
