(define (problem libros)
(:domain libros)
(:objects m1 m2 m3 m4 m5 m6 m6 m7 m8 m9 m10 m11 m12 - Mes
vulputate_justo maecenas_rhoncus_aliquam dui_proin est_congue aliquam_non_mauris odio_donec_vitae orci amet dolor_vel_est ante_ipsum_primis_1 ante_ipsum_primis_2 ante_ipsum_primis_3 ante_ipsum_primis_4 ante_ipsum_primis_5 - Libro
)
(:init
(paralelo ante_ipsum_primis_5 dui_proin)
(paralelo amet ante_ipsum_primis_2)
(paralelo vulputate_justo ante_ipsum_primis_3)
(predecesor ante_ipsum_primis_1 ante_ipsum_primis_2)
(predecesor ante_ipsum_primis_2 ante_ipsum_primis_3)
(predecesor ante_ipsum_primis_3 ante_ipsum_primis_4)
(predecesor ante_ipsum_primis_4 ante_ipsum_primis_5)
(libro_leido orci)
(libro_leido dui_proin)
(libro_leido vulputate_justo)
(libro_a_leer dolor_vel_est)
(libro_a_leer aliquam_non_mauris)
(libro_a_leer ante_ipsum_primis_5)
(anterior m1 m2) (anterior m1 m3) (anterior m1 m4) (anterior m1 m5) (anterior m1 m6) (anterior m1 m7)
(anterior m1 m8) (anterior m1 m9) (anterior m1 m10) (anterior m1 m11) (anterior m1 m12)
(anterior m2 m3) (anterior m2 m4) (anterior m2 m5) (anterior m2 m6) (anterior m2 m7) (anterior m2 m8)
(anterior m2 m9) (anterior m2 m10) (anterior m2 m11) (anterior m2 m12)
(anterior m3 m4) (anterior m3 m5) (anterior m3 m6) (anterior m3 m7) (anterior m3 m8) (anterior m3 m9)
(anterior m3 m10) (anterior m3 m11) (anterior m3 m12)
(anterior m4 m5) (anterior m4 m6) (anterior m4 m7) (anterior m4 m8) (anterior m4 m9) (anterior m4 m10)
(anterior m4 m11) (anterior m4 m12) (anterior m5 m6) (anterior m5 m7) (anterior m5 m8) (anterior m5 m9) (anterior m5 m10) (anterior m5 m11)
(anterior m5 m12) (anterior m6 m7) (anterior m6 m8) (anterior m6 m9) (anterior m6 m10) (anterior m6 m11) (anterior m6 m12)
(anterior m7 m8) (anterior m7 m9) (anterior m7 m10) (anterior m7 m11) (anterior m7 m12) (anterior m8 m9) (anterior m8 m10) (anterior m8 m11) (anterior m8 m12)
(anterior m9 m10) (anterior m9 m11) (anterior m9 m12) (anterior m10 m11) (anterior m10 m12) (anterior m11 m12)
)
(:goal (forall (?l - Libro) (imply (libro_a_leer ?l) (libro_asignado ?l)))))
