(define (problem libros)
(:domain libros)
(:objects m1 m2 m3 m4 m5 m6 m6 m7 m8 m9 m10 m11 m12 - Mes
ipsum ut vitae_nisl eros massa_donec iaculis_congue_vivamus congue_vivamus sem eget_eros turpis ipsum ultrices_posuere_cubilia vel_sem_sed interdum vel_lectus nonummy_integer_non id_nulla_ultrices lectus_pellentesque sapien eget felis_donec proin in molestie morbi_non_quam ligula_vehicula massa_id_nisl pede_ullamcorper et proin_risus nulla amet lobortis_sapien odio_curabitur_convallis proin_eu suscipit_nulla_elit augue_a morbi_vestibulum ac_neque_duis amet justo_nec_condimentum aliquam_non_mauris nisi_volutpat_eleifend maecenas_rhoncus_aliquam_1 maecenas_rhoncus_aliquam_2 maecenas_rhoncus_aliquam_3 maecenas_rhoncus_aliquam_4 ipsum_1 ipsum_2 ipsum_3 imperdiet_sapien_urna_1 imperdiet_sapien_urna_2 imperdiet_sapien_urna_3 imperdiet_sapien_urna_4 imperdiet_sapien_urna_5 imperdiet_sapien_urna_6 imperdiet_sapien_urna_7 nam_dui_1 nam_dui_2 nam_dui_3 imperdiet_et_1 imperdiet_et_2 imperdiet_et_3 in_blandit_ultrices_1 in_blandit_ultrices_2 in_blandit_ultrices_3 metus_1 metus_2 - Libro
)
(:init
(paralelo imperdiet_sapien_urna_5 ultrices_posuere_cubilia)
(predecesor maecenas_rhoncus_aliquam_1 maecenas_rhoncus_aliquam_2)
(predecesor maecenas_rhoncus_aliquam_2 maecenas_rhoncus_aliquam_3)
(predecesor maecenas_rhoncus_aliquam_3 maecenas_rhoncus_aliquam_4)
(predecesor ipsum_1 ipsum_2)
(predecesor ipsum_2 ipsum_3)
(predecesor imperdiet_sapien_urna_1 imperdiet_sapien_urna_2)
(predecesor imperdiet_sapien_urna_2 imperdiet_sapien_urna_3)
(predecesor imperdiet_sapien_urna_3 imperdiet_sapien_urna_4)
(predecesor imperdiet_sapien_urna_4 imperdiet_sapien_urna_5)
(predecesor imperdiet_sapien_urna_5 imperdiet_sapien_urna_6)
(predecesor imperdiet_sapien_urna_6 imperdiet_sapien_urna_7)
(predecesor nam_dui_1 nam_dui_2)
(predecesor nam_dui_2 nam_dui_3)
(predecesor imperdiet_et_1 imperdiet_et_2)
(predecesor imperdiet_et_2 imperdiet_et_3)
(predecesor in_blandit_ultrices_1 in_blandit_ultrices_2)
(predecesor in_blandit_ultrices_2 in_blandit_ultrices_3)
(predecesor metus_1 metus_2)
(libro_leido interdum)
(libro_leido sapien)
(libro_leido vel_sem_sed)
(libro_leido vel_lectus)
(libro_a_leer imperdiet_sapien_urna_7)
(libro_a_leer imperdiet_sapien_urna_5)
(libro_a_leer eros)
(libro_a_leer ipsum_2)
(libro_a_leer ipsum_1)
(libro_a_leer felis_donec)
(libro_a_leer nam_dui_3)
(libro_a_leer nam_dui_2)
(libro_a_leer imperdiet_sapien_urna_4)
(libro_a_leer aliquam_non_mauris)
(libro_a_leer pede_ullamcorper)
(libro_a_leer vitae_nisl)
(libro_a_leer proin_risus)
(libro_a_leer morbi_non_quam)
(libro_a_leer massa_id_nisl)
(libro_a_leer in_blandit_ultrices_2)
(libro_a_leer in_blandit_ultrices_3)
(libro_a_leer ipsum)
(libro_a_leer id_nulla_ultrices)
(libro_a_leer suscipit_nulla_elit)
(libro_a_leer nulla)
(libro_a_leer augue_a)
(libro_a_leer proin)
(anterior m1 m2) (anterior m1 m3) (anterior m1 m4) (anterior m1 m5) (anterior m1 m6) (anterior m1 m7)
(anterior m1 m8) (anterior m1 m9) (anterior m1 m10) (anterior m1 m11) (anterior m1 m12)
(anterior m2 m3) (anterior m2 m4) (anterior m2 m5) (anterior m2 m6) (anterior m2 m7) (anterior m2 m8)
(anterior m2 m9) (anterior m2 m10) (anterior m2 m11) (anterior m2 m12)
(anterior m3 m4) (anterior m3 m5) (anterior m3 m6) (anterior m3 m7) (anterior m3 m8) (anterior m3 m9)
(anterior m3 m10) (anterior m3 m11) (anterior m3 m12)
(anterior m4 m5) (anterior m4 m6) (anterior m4 m7) (anterior m4 m8) (anterior m4 m9) (anterior m4 m10)
(anterior m4 m11) (anterior m4 m12) (anterior m5 m6) (anterior m5 m7) (anterior m5 m8) (anterior m5 m9) (anterior m5 m10) (anterior m5 m11)
(anterior m5 m12) (anterior m6 m7) (anterior m6 m8) (anterior m6 m9) (anterior m6 m10) (anterior m6 m11) (anterior m6 m12)
(anterior m7 m8) (anterior m7 m9) (anterior m7 m10) (anterior m7 m11) (anterior m7 m12) (anterior m8 m9) (anterior m8 m10) (anterior m8 m11) (anterior m8 m12)
(anterior m9 m10) (anterior m9 m11) (anterior m9 m12) (anterior m10 m11) (anterior m10 m12) (anterior m11 m12)
)
(:goal (forall (?l - Libro) (imply (libro_a_leer ?l) (libro_asignado ?l)))))
