(define (problem libros)
(:domain libros)
(:objects m1 m2 m3 m4 m5 m6 m6 m7 m8 m9 m10 m11 m12 - Mes
libero_nam lacus_at cursus id_ornare semper_sapien pharetra nulla_sed congue luctus_et nisi_at rhoncus_mauris vulputate_justo nulla_integer ac_nibh_fusce ut_blandit blandit enim_sit_amet eu_magna dui_nec a_suscipit justo_pellentesque donec nulla parturient felis_donec_semper rhoncus in euismod_scelerisque cursus_vestibulum eu libero_quis_orci integer cubilia_curae elementum ut curae_donec enim_lorem odio leo_pellentesque nonummy_integer_non mus_vivamus vel proin_interdum_mauris turpis etiam_justo massa_donec_dapibus id_consequat_in donec eros convallis_nunc_proin eget_tincidunt_eget quisque_porta neque_sapien_placerat eget in sagittis_nam sagittis sapien_placerat sed_interdum id_massa_id fusce_congue_diam ac_est lacinia_sapien et nam_ultrices_libero elit in_imperdiet_et bibendum_felis_sed pellentesque semper_porta_volutpat rutrum_neque nisl_venenatis a_ipsum_integer morbi_vel_lectus_1 morbi_vel_lectus_2 morbi_vel_lectus_3 morbi_vel_lectus_4 morbi_vel_lectus_5 morbi_vel_lectus_6 ac_1 ac_2 imperdiet_sapien_urna_1 imperdiet_sapien_urna_2 imperdiet_sapien_urna_3 imperdiet_sapien_urna_4 duis_ac_1 duis_ac_2 pede_posuere_nonummy_1 pede_posuere_nonummy_2 pede_posuere_nonummy_3 pede_posuere_nonummy_4 pede_posuere_nonummy_5 pede_posuere_nonummy_6 pede_posuere_nonummy_7 dui_luctus_rutrum_1 dui_luctus_rutrum_2 dui_luctus_rutrum_3 tortor_1 tortor_2 tortor_3 tortor_4 tortor_5 tortor_6 - Libro
)
(:init
(paralelo sagittis_nam tortor_6)
(predecesor morbi_vel_lectus_1 morbi_vel_lectus_2)
(predecesor morbi_vel_lectus_2 morbi_vel_lectus_3)
(predecesor morbi_vel_lectus_3 morbi_vel_lectus_4)
(predecesor morbi_vel_lectus_4 morbi_vel_lectus_5)
(predecesor morbi_vel_lectus_5 morbi_vel_lectus_6)
(predecesor ac_1 ac_2)
(predecesor imperdiet_sapien_urna_1 imperdiet_sapien_urna_2)
(predecesor imperdiet_sapien_urna_2 imperdiet_sapien_urna_3)
(predecesor imperdiet_sapien_urna_3 imperdiet_sapien_urna_4)
(predecesor duis_ac_1 duis_ac_2)
(predecesor pede_posuere_nonummy_1 pede_posuere_nonummy_2)
(predecesor pede_posuere_nonummy_2 pede_posuere_nonummy_3)
(predecesor pede_posuere_nonummy_3 pede_posuere_nonummy_4)
(predecesor pede_posuere_nonummy_4 pede_posuere_nonummy_5)
(predecesor pede_posuere_nonummy_5 pede_posuere_nonummy_6)
(predecesor pede_posuere_nonummy_6 pede_posuere_nonummy_7)
(predecesor dui_luctus_rutrum_1 dui_luctus_rutrum_2)
(predecesor dui_luctus_rutrum_2 dui_luctus_rutrum_3)
(predecesor tortor_1 tortor_2)
(predecesor tortor_2 tortor_3)
(predecesor tortor_3 tortor_4)
(predecesor tortor_4 tortor_5)
(predecesor tortor_5 tortor_6)
(libro_leido cubilia_curae)
(libro_leido nam_ultrices_libero)
(libro_leido eget_tincidunt_eget)
(libro_leido sagittis)
(libro_leido nonummy_integer_non)
(libro_leido elit)
(libro_leido in)
(libro_leido eu)
(libro_leido et)
(libro_leido dui_nec)
(libro_leido eros)
(libro_leido id_consequat_in)
(libro_leido ac_est)
(libro_leido euismod_scelerisque)
(libro_leido mus_vivamus)
(libro_leido eget)
(libro_leido proin_interdum_mauris)
(libro_leido lacus_at)
(libro_leido felis_donec_semper)
(libro_leido in_imperdiet_et)
(libro_leido nulla_sed)
(libro_leido luctus_et)
(libro_leido elementum)
(libro_leido semper_porta_volutpat)
(libro_leido congue)
(libro_leido a_ipsum_integer)
(libro_leido turpis)
(libro_leido cursus_vestibulum)
(libro_leido leo_pellentesque)
(libro_leido donec)
(libro_leido cursus)
(libro_leido odio)
(libro_leido sapien_placerat)
(libro_leido neque_sapien_placerat)
(libro_leido libero_nam)
(libro_leido curae_donec)
(libro_leido fusce_congue_diam)
(libro_leido quisque_porta)
(libro_leido ut)
(libro_leido eu_magna)
(libro_leido nisi_at)
(libro_leido pellentesque)
(libro_leido id_ornare)
(libro_leido nulla)
(libro_leido ac_nibh_fusce)
(libro_a_leer justo_pellentesque)
(libro_a_leer vel)
(anterior m1 m2) (anterior m1 m3) (anterior m1 m4) (anterior m1 m5) (anterior m1 m6) (anterior m1 m7)
(anterior m1 m8) (anterior m1 m9) (anterior m1 m10) (anterior m1 m11) (anterior m1 m12)
(anterior m2 m3) (anterior m2 m4) (anterior m2 m5) (anterior m2 m6) (anterior m2 m7) (anterior m2 m8)
(anterior m2 m9) (anterior m2 m10) (anterior m2 m11) (anterior m2 m12)
(anterior m3 m4) (anterior m3 m5) (anterior m3 m6) (anterior m3 m7) (anterior m3 m8) (anterior m3 m9)
(anterior m3 m10) (anterior m3 m11) (anterior m3 m12)
(anterior m4 m5) (anterior m4 m6) (anterior m4 m7) (anterior m4 m8) (anterior m4 m9) (anterior m4 m10)
(anterior m4 m11) (anterior m4 m12) (anterior m5 m6) (anterior m5 m7) (anterior m5 m8) (anterior m5 m9) (anterior m5 m10) (anterior m5 m11)
(anterior m5 m12) (anterior m6 m7) (anterior m6 m8) (anterior m6 m9) (anterior m6 m10) (anterior m6 m11) (anterior m6 m12)
(anterior m7 m8) (anterior m7 m9) (anterior m7 m10) (anterior m7 m11) (anterior m7 m12) (anterior m8 m9) (anterior m8 m10) (anterior m8 m11) (anterior m8 m12)
(anterior m9 m10) (anterior m9 m11) (anterior m9 m12) (anterior m10 m11) (anterior m10 m12) (anterior m11 m12)
)
(:goal (forall (?l - Libro) (imply (libro_a_leer ?l) (libro_asignado ?l)))))
