(define (problem libros)
(:domain libros)
(:objects m1 m2 m3 m4 m5 m6 m6 m7 m8 m9 m10 m11 m12 - Mes
elit turpis libero congue_etiam non_interdum_in ac_est mi_integer at_nulla est in_tempor_turpis quis_orci iaculis_congue_vivamus elementum_nullam_varius id_ornare ultrices_mattis_odio integer odio_elementum_eu id_pretium vel nam_dui elit at commodo_vulputate dui_proin_leo mauris_viverra_diam in accumsan_tellus integer eu_sapien donec_ut sed augue_vel rhoncus_mauris tortor_id aliquet_massa_id vestibulum_sed_magna amet lacus_at tortor nulla_suscipit_ligula imperdiet_et erat_eros cum_sociis_natoque augue lectus_in est_lacinia_nisi lectus proin_at est_et in_blandit_ultrices nulla_eget_eros urna nulla at_ipsum lectus_in mattis_odio_donec metus_aenean primis_in_faucibus nulla_sed morbi_vestibulum luctus_et gravida_sem_praesent vestibulum_sagittis_sapien elit et_magnis euismod_scelerisque elementum_pellentesque_quisque semper_sapien_a orci_nullam_molestie consequat sit at suscipit amet nulla_integer nulla_sed sem amet elit risus_dapibus_augue arcu ultrices dapibus_duis_at nisi_volutpat_eleifend lacus_purus_aliquet et_1 et_2 et_3 et_4 et_5 auctor_sed_1 auctor_sed_2 auctor_sed_3 auctor_sed_4 auctor_sed_5 auctor_sed_6 auctor_sed_7 in_1 in_2 in_3 in_4 molestie_lorem_quisque_1 molestie_lorem_quisque_2 molestie_lorem_quisque_3 molestie_lorem_quisque_4 molestie_lorem_quisque_5 leo_pellentesque_1 leo_pellentesque_2 leo_pellentesque_3 leo_pellentesque_4 leo_pellentesque_5 leo_pellentesque_6 praesent_blandit_1 praesent_blandit_2 praesent_blandit_3 praesent_blandit_4 cubilia_curae_donec_1 cubilia_curae_donec_2 cubilia_curae_donec_3 luctus_et_ultrices_1 luctus_et_ultrices_2 amet_cursus_1 amet_cursus_2 amet_cursus_3 proin_eu_mi_1 proin_eu_mi_2 ornare_consequat_1 ornare_consequat_2 ornare_consequat_3 ornare_consequat_4 viverra_eget_congue_1 viverra_eget_congue_2 viverra_eget_congue_3 viverra_eget_congue_4 nisi_1 nisi_2 nisi_3 nisi_4 nisi_5 nisi_6 nisi_7 varius_ut_blandit_1 varius_ut_blandit_2 varius_ut_blandit_3 varius_ut_blandit_4 habitasse_1 habitasse_2 habitasse_3 habitasse_4 habitasse_5 habitasse_6 - Libro
)
(:init
(paralelo cubilia_curae_donec_1 dui_proin_leo)
(paralelo et_magnis ultrices)
(predecesor et_1 et_2)
(predecesor et_2 et_3)
(predecesor et_3 et_4)
(predecesor et_4 et_5)
(predecesor auctor_sed_1 auctor_sed_2)
(predecesor auctor_sed_2 auctor_sed_3)
(predecesor auctor_sed_3 auctor_sed_4)
(predecesor auctor_sed_4 auctor_sed_5)
(predecesor auctor_sed_5 auctor_sed_6)
(predecesor auctor_sed_6 auctor_sed_7)
(predecesor in_1 in_2)
(predecesor in_2 in_3)
(predecesor in_3 in_4)
(predecesor molestie_lorem_quisque_1 molestie_lorem_quisque_2)
(predecesor molestie_lorem_quisque_2 molestie_lorem_quisque_3)
(predecesor molestie_lorem_quisque_3 molestie_lorem_quisque_4)
(predecesor molestie_lorem_quisque_4 molestie_lorem_quisque_5)
(predecesor leo_pellentesque_1 leo_pellentesque_2)
(predecesor leo_pellentesque_2 leo_pellentesque_3)
(predecesor leo_pellentesque_3 leo_pellentesque_4)
(predecesor leo_pellentesque_4 leo_pellentesque_5)
(predecesor leo_pellentesque_5 leo_pellentesque_6)
(predecesor praesent_blandit_1 praesent_blandit_2)
(predecesor praesent_blandit_2 praesent_blandit_3)
(predecesor praesent_blandit_3 praesent_blandit_4)
(predecesor cubilia_curae_donec_1 cubilia_curae_donec_2)
(predecesor cubilia_curae_donec_2 cubilia_curae_donec_3)
(predecesor luctus_et_ultrices_1 luctus_et_ultrices_2)
(predecesor amet_cursus_1 amet_cursus_2)
(predecesor amet_cursus_2 amet_cursus_3)
(predecesor proin_eu_mi_1 proin_eu_mi_2)
(predecesor ornare_consequat_1 ornare_consequat_2)
(predecesor ornare_consequat_2 ornare_consequat_3)
(predecesor ornare_consequat_3 ornare_consequat_4)
(predecesor viverra_eget_congue_1 viverra_eget_congue_2)
(predecesor viverra_eget_congue_2 viverra_eget_congue_3)
(predecesor viverra_eget_congue_3 viverra_eget_congue_4)
(predecesor nisi_1 nisi_2)
(predecesor nisi_2 nisi_3)
(predecesor nisi_3 nisi_4)
(predecesor nisi_4 nisi_5)
(predecesor nisi_5 nisi_6)
(predecesor nisi_6 nisi_7)
(predecesor varius_ut_blandit_1 varius_ut_blandit_2)
(predecesor varius_ut_blandit_2 varius_ut_blandit_3)
(predecesor varius_ut_blandit_3 varius_ut_blandit_4)
(predecesor habitasse_1 habitasse_2)
(predecesor habitasse_2 habitasse_3)
(predecesor habitasse_3 habitasse_4)
(predecesor habitasse_4 habitasse_5)
(predecesor habitasse_5 habitasse_6)
(libro_leido accumsan_tellus)
(libro_leido ultrices)
(libro_leido odio_elementum_eu)
(libro_leido nam_dui)
(libro_leido at)
(libro_leido in)
(libro_leido sem)
(libro_leido nulla_suscipit_ligula)
(libro_leido ac_est)
(libro_leido elementum_nullam_varius)
(libro_leido nulla_integer)
(libro_leido sit)
(libro_leido mauris_viverra_diam)
(libro_leido erat_eros)
(libro_leido vel)
(libro_leido congue_etiam)
(libro_leido in_tempor_turpis)
(libro_leido augue_vel)
(libro_leido non_interdum_in)
(libro_leido consequat)
(libro_leido integer)
(libro_leido ultrices_mattis_odio)
(libro_leido primis_in_faucibus)
(libro_leido donec_ut)
(libro_leido nulla)
(libro_a_leer viverra_eget_congue_1)
(libro_a_leer aliquet_massa_id)
(libro_a_leer viverra_eget_congue_4)
(libro_a_leer lectus_in)
(libro_a_leer habitasse_1)
(libro_a_leer semper_sapien_a)
(libro_a_leer varius_ut_blandit_2)
(libro_a_leer risus_dapibus_augue)
(libro_a_leer at_ipsum)
(libro_a_leer molestie_lorem_quisque_5)
(libro_a_leer molestie_lorem_quisque_2)
(libro_a_leer cubilia_curae_donec_1)
(libro_a_leer praesent_blandit_4)
(libro_a_leer cubilia_curae_donec_3)
(libro_a_leer praesent_blandit_3)
(libro_a_leer praesent_blandit_1)
(libro_a_leer nisi_volutpat_eleifend)
(libro_a_leer commodo_vulputate)
(libro_a_leer leo_pellentesque_2)
(libro_a_leer arcu)
(libro_a_leer ornare_consequat_2)
(libro_a_leer ornare_consequat_3)
(libro_a_leer nisi_1)
(libro_a_leer nisi_4)
(libro_a_leer nisi_7)
(libro_a_leer auctor_sed_4)
(libro_a_leer morbi_vestibulum)
(libro_a_leer in_1)
(libro_a_leer auctor_sed_2)
(libro_a_leer auctor_sed_3)
(libro_a_leer et_4)
(libro_a_leer imperdiet_et)
(libro_a_leer amet)
(libro_a_leer et_5)
(libro_a_leer mi_integer)
(libro_a_leer id_pretium)
(libro_a_leer sed)
(libro_a_leer luctus_et_ultrices_2)
(libro_a_leer et_magnis)
(libro_a_leer vestibulum_sed_magna)
(libro_a_leer quis_orci)
(libro_a_leer habitasse_2)
(libro_a_leer amet_cursus_2)
(libro_a_leer proin_at)
(libro_a_leer dapibus_duis_at)
(libro_a_leer nulla_sed)
(libro_a_leer cum_sociis_natoque)
(anterior m1 m2) (anterior m1 m3) (anterior m1 m4) (anterior m1 m5) (anterior m1 m6) (anterior m1 m7)
(anterior m1 m8) (anterior m1 m9) (anterior m1 m10) (anterior m1 m11) (anterior m1 m12)
(anterior m2 m3) (anterior m2 m4) (anterior m2 m5) (anterior m2 m6) (anterior m2 m7) (anterior m2 m8)
(anterior m2 m9) (anterior m2 m10) (anterior m2 m11) (anterior m2 m12)
(anterior m3 m4) (anterior m3 m5) (anterior m3 m6) (anterior m3 m7) (anterior m3 m8) (anterior m3 m9)
(anterior m3 m10) (anterior m3 m11) (anterior m3 m12)
(anterior m4 m5) (anterior m4 m6) (anterior m4 m7) (anterior m4 m8) (anterior m4 m9) (anterior m4 m10)
(anterior m4 m11) (anterior m4 m12) (anterior m5 m6) (anterior m5 m7) (anterior m5 m8) (anterior m5 m9) (anterior m5 m10) (anterior m5 m11)
(anterior m5 m12) (anterior m6 m7) (anterior m6 m8) (anterior m6 m9) (anterior m6 m10) (anterior m6 m11) (anterior m6 m12)
(anterior m7 m8) (anterior m7 m9) (anterior m7 m10) (anterior m7 m11) (anterior m7 m12) (anterior m8 m9) (anterior m8 m10) (anterior m8 m11) (anterior m8 m12)
(anterior m9 m10) (anterior m9 m11) (anterior m9 m12) (anterior m10 m11) (anterior m10 m12) (anterior m11 m12)
)
(:goal (forall (?l - Libro) (imply (libro_a_leer ?l) (libro_asignado ?l)))))
