(define (problem libros)
(:domain libros)
(:objects m1 m2 m3 m4 m5 m6 m6 m7 m8 m9 m10 m11 m12 - Mes
semper eros elementum_nullam_varius rutrum_ac_lobortis nam_dui eros_elementum_pellentesque dapibus sem_fusce dui_vel_nisl eget dui_proin_leo nisi semper_sapien_a dui nulla_nunc curabitur morbi arcu ac_est quam_suspendisse_potenti non interdum nisl_nunc_nisl praesent_blandit ultrices_posuere massa_donec_dapibus nulla_tellus id tincidunt proin_interdum_mauris lacinia_sapien quisque_porta at vehicula_consequat dui lorem_id_ligula etiam quisque_porta_volutpat arcu_sed_augue donec_dapibus vitae_mattis_nibh arcu_adipiscing nisi_venenatis_tristique vitae_nisl pharetra_magna aliquam sapien lectus_aliquam mauris_eget_massa fusce_consequat sit_amet_diam_1 sit_amet_diam_2 sit_amet_diam_3 sit_amet_diam_4 sit_amet_diam_5 sit_amet_diam_6 dictumst_1 dictumst_2 dictumst_3 dictumst_4 non_sodales_1 non_sodales_2 non_sodales_3 non_sodales_4 iaculis_congue_vivamus_1 iaculis_congue_vivamus_2 ligula_sit_amet_1 ligula_sit_amet_2 ligula_sit_amet_3 ligula_sit_amet_4 ligula_sit_amet_5 ligula_sit_amet_6 ridiculus_mus_1 ridiculus_mus_2 montes_nascetur_1 montes_nascetur_2 montes_nascetur_3 montes_nascetur_4 amet_1 amet_2 amet_3 amet_4 amet_5 donec_1 donec_2 donec_3 donec_4 donec_5 donec_6 donec_7 ipsum_1 ipsum_2 ipsum_3 ipsum_4 ipsum_5 ipsum_6 ipsum_7 - Libro
)
(:init
(paralelo iaculis_congue_vivamus_2 curabitur)
(paralelo ridiculus_mus_1 morbi)
(paralelo tincidunt amet_2)
(predecesor sit_amet_diam_1 sit_amet_diam_2)
(predecesor sit_amet_diam_2 sit_amet_diam_3)
(predecesor sit_amet_diam_3 sit_amet_diam_4)
(predecesor sit_amet_diam_4 sit_amet_diam_5)
(predecesor sit_amet_diam_5 sit_amet_diam_6)
(predecesor dictumst_1 dictumst_2)
(predecesor dictumst_2 dictumst_3)
(predecesor dictumst_3 dictumst_4)
(predecesor non_sodales_1 non_sodales_2)
(predecesor non_sodales_2 non_sodales_3)
(predecesor non_sodales_3 non_sodales_4)
(predecesor iaculis_congue_vivamus_1 iaculis_congue_vivamus_2)
(predecesor ligula_sit_amet_1 ligula_sit_amet_2)
(predecesor ligula_sit_amet_2 ligula_sit_amet_3)
(predecesor ligula_sit_amet_3 ligula_sit_amet_4)
(predecesor ligula_sit_amet_4 ligula_sit_amet_5)
(predecesor ligula_sit_amet_5 ligula_sit_amet_6)
(predecesor ridiculus_mus_1 ridiculus_mus_2)
(predecesor montes_nascetur_1 montes_nascetur_2)
(predecesor montes_nascetur_2 montes_nascetur_3)
(predecesor montes_nascetur_3 montes_nascetur_4)
(predecesor amet_1 amet_2)
(predecesor amet_2 amet_3)
(predecesor amet_3 amet_4)
(predecesor amet_4 amet_5)
(predecesor donec_1 donec_2)
(predecesor donec_2 donec_3)
(predecesor donec_3 donec_4)
(predecesor donec_4 donec_5)
(predecesor donec_5 donec_6)
(predecesor donec_6 donec_7)
(predecesor ipsum_1 ipsum_2)
(predecesor ipsum_2 ipsum_3)
(predecesor ipsum_3 ipsum_4)
(predecesor ipsum_4 ipsum_5)
(predecesor ipsum_5 ipsum_6)
(predecesor ipsum_6 ipsum_7)
(libro_leido arcu_sed_augue)
(libro_leido arcu)
(libro_leido elementum_nullam_varius)
(libro_leido fusce_consequat)
(libro_leido dapibus)
(libro_leido pharetra_magna)
(libro_leido mauris_eget_massa)
(libro_leido dui)
(libro_leido dui_proin_leo)
(libro_leido lectus_aliquam)
(libro_leido vehicula_consequat)
(libro_leido at)
(libro_leido nulla_tellus)
(libro_leido donec_dapibus)
(libro_a_leer donec_5)
(libro_a_leer donec_4)
(libro_a_leer montes_nascetur_1)
(libro_a_leer donec_1)
(libro_a_leer montes_nascetur_4)
(libro_a_leer semper)
(libro_a_leer amet_5)
(libro_a_leer curabitur)
(libro_a_leer sem_fusce)
(libro_a_leer quam_suspendisse_potenti)
(libro_a_leer vitae_mattis_nibh)
(libro_a_leer id)
(libro_a_leer proin_interdum_mauris)
(libro_a_leer dictumst_3)
(libro_a_leer dictumst_4)
(libro_a_leer ipsum_4)
(libro_a_leer ipsum_1)
(libro_a_leer iaculis_congue_vivamus_1)
(libro_a_leer etiam)
(libro_a_leer lorem_id_ligula)
(libro_a_leer non_sodales_1)
(libro_a_leer non_sodales_3)
(libro_a_leer non_sodales_2)
(libro_a_leer non_sodales_4)
(libro_a_leer ultrices_posuere)
(libro_a_leer lacinia_sapien)
(libro_a_leer ac_est)
(libro_a_leer morbi)
(libro_a_leer sit_amet_diam_4)
(libro_a_leer sit_amet_diam_6)
(libro_a_leer nisi)
(libro_a_leer quisque_porta)
(libro_a_leer ligula_sit_amet_5)
(libro_a_leer ligula_sit_amet_6)
(libro_a_leer ligula_sit_amet_1)
(libro_a_leer eros_elementum_pellentesque)
(anterior m1 m2) (anterior m1 m3) (anterior m1 m4) (anterior m1 m5) (anterior m1 m6) (anterior m1 m7)
(anterior m1 m8) (anterior m1 m9) (anterior m1 m10) (anterior m1 m11) (anterior m1 m12)
(anterior m2 m3) (anterior m2 m4) (anterior m2 m5) (anterior m2 m6) (anterior m2 m7) (anterior m2 m8)
(anterior m2 m9) (anterior m2 m10) (anterior m2 m11) (anterior m2 m12)
(anterior m3 m4) (anterior m3 m5) (anterior m3 m6) (anterior m3 m7) (anterior m3 m8) (anterior m3 m9)
(anterior m3 m10) (anterior m3 m11) (anterior m3 m12)
(anterior m4 m5) (anterior m4 m6) (anterior m4 m7) (anterior m4 m8) (anterior m4 m9) (anterior m4 m10)
(anterior m4 m11) (anterior m4 m12) (anterior m5 m6) (anterior m5 m7) (anterior m5 m8) (anterior m5 m9) (anterior m5 m10) (anterior m5 m11)
(anterior m5 m12) (anterior m6 m7) (anterior m6 m8) (anterior m6 m9) (anterior m6 m10) (anterior m6 m11) (anterior m6 m12)
(anterior m7 m8) (anterior m7 m9) (anterior m7 m10) (anterior m7 m11) (anterior m7 m12) (anterior m8 m9) (anterior m8 m10) (anterior m8 m11) (anterior m8 m12)
(anterior m9 m10) (anterior m9 m11) (anterior m9 m12) (anterior m10 m11) (anterior m10 m12) (anterior m11 m12)
)
(:goal (forall (?l - Libro) (imply (libro_a_leer ?l) (libro_asignado ?l)))))
