(define (problem libros)
(:domain libros)
(:objects m1 m2 m3 m4 m5 m6 m6 m7 m8 m9 m10 m11 m12 - Mes
vestibulum_sit purus_aliquet_at pede_venenatis rhoncus lacinia_nisi_venenatis enim_sit faucibus_orci vel_enim curabitur condimentum_id turpis_nec morbi_vel_lectus sapien_a luctus_et in consequat ligula_sit_amet ut_mauris_eget odio_elementum_eu vulputate_justo integer_aliquet nascetur aliquam nulla_tellus amet libero et_1 et_2 et_3 ipsum_1 ipsum_2 rutrum_nulla_tellus_1 rutrum_nulla_tellus_2 aenean_1 aenean_2 aenean_3 aenean_4 - Libro
)
(:init
(paralelo ligula_sit_amet aenean_1)
(predecesor et_1 et_2)
(predecesor et_2 et_3)
(predecesor ipsum_1 ipsum_2)
(predecesor rutrum_nulla_tellus_1 rutrum_nulla_tellus_2)
(predecesor aenean_1 aenean_2)
(predecesor aenean_2 aenean_3)
(predecesor aenean_3 aenean_4)
(libro_leido pede_venenatis)
(libro_leido turpis_nec)
(libro_leido lacinia_nisi_venenatis)
(libro_leido odio_elementum_eu)
(libro_leido nascetur)
(libro_leido ut_mauris_eget)
(libro_leido purus_aliquet_at)
(libro_leido morbi_vel_lectus)
(libro_leido ligula_sit_amet)
(libro_leido vel_enim)
(libro_leido condimentum_id)
(libro_leido amet)
(libro_leido aliquam)
(libro_a_leer vestibulum_sit)
(libro_a_leer et_2)
(libro_a_leer vulputate_justo)
(anterior m1 m2) (anterior m1 m3) (anterior m1 m4) (anterior m1 m5) (anterior m1 m6) (anterior m1 m7)
(anterior m1 m8) (anterior m1 m9) (anterior m1 m10) (anterior m1 m11) (anterior m1 m12)
(anterior m2 m3) (anterior m2 m4) (anterior m2 m5) (anterior m2 m6) (anterior m2 m7) (anterior m2 m8)
(anterior m2 m9) (anterior m2 m10) (anterior m2 m11) (anterior m2 m12)
(anterior m3 m4) (anterior m3 m5) (anterior m3 m6) (anterior m3 m7) (anterior m3 m8) (anterior m3 m9)
(anterior m3 m10) (anterior m3 m11) (anterior m3 m12)
(anterior m4 m5) (anterior m4 m6) (anterior m4 m7) (anterior m4 m8) (anterior m4 m9) (anterior m4 m10)
(anterior m4 m11) (anterior m4 m12) (anterior m5 m6) (anterior m5 m7) (anterior m5 m8) (anterior m5 m9) (anterior m5 m10) (anterior m5 m11)
(anterior m5 m12) (anterior m6 m7) (anterior m6 m8) (anterior m6 m9) (anterior m6 m10) (anterior m6 m11) (anterior m6 m12)
(anterior m7 m8) (anterior m7 m9) (anterior m7 m10) (anterior m7 m11) (anterior m7 m12) (anterior m8 m9) (anterior m8 m10) (anterior m8 m11) (anterior m8 m12)
(anterior m9 m10) (anterior m9 m11) (anterior m9 m12) (anterior m10 m11) (anterior m10 m12) (anterior m11 m12)
)
(:goal (forall (?l - Libro) (imply (libro_a_leer ?l) (libro_asignado ?l)))))
