(define (problem libros)
(:domain libros)
(:objects m1 m2 m3 m4 m5 m6 m6 m7 m8 m9 m10 m11 m12 - Mes
interdum nulla sem_mauris adipiscing dictumst fermentum_donec augue_vel_accumsan proin_eu nullam_varius diam_nam non_quam_nec dolor_morbi nulla dapibus_nulla_suscipit lacinia_sapien nascetur dui_luctus_rutrum sed_interdum_venenatis parturient ipsum_primis_in_1 ipsum_primis_in_2 - Libro
)
(:init
(predecesor ipsum_primis_in_1 ipsum_primis_in_2)
(libro_leido sed_interdum_venenatis)
(libro_leido interdum)
(libro_leido sem_mauris)
(libro_leido dapibus_nulla_suscipit)
(libro_leido adipiscing)
(libro_leido nullam_varius)
(libro_leido nulla)
(libro_leido non_quam_nec)
(libro_leido fermentum_donec)
(libro_leido augue_vel_accumsan)
(libro_leido dolor_morbi)
(libro_a_leer dui_luctus_rutrum)
(anterior m1 m2) (anterior m1 m3) (anterior m1 m4) (anterior m1 m5) (anterior m1 m6) (anterior m1 m7)
(anterior m1 m8) (anterior m1 m9) (anterior m1 m10) (anterior m1 m11) (anterior m1 m12)
(anterior m2 m3) (anterior m2 m4) (anterior m2 m5) (anterior m2 m6) (anterior m2 m7) (anterior m2 m8)
(anterior m2 m9) (anterior m2 m10) (anterior m2 m11) (anterior m2 m12)
(anterior m3 m4) (anterior m3 m5) (anterior m3 m6) (anterior m3 m7) (anterior m3 m8) (anterior m3 m9)
(anterior m3 m10) (anterior m3 m11) (anterior m3 m12)
(anterior m4 m5) (anterior m4 m6) (anterior m4 m7) (anterior m4 m8) (anterior m4 m9) (anterior m4 m10)
(anterior m4 m11) (anterior m4 m12) (anterior m5 m6) (anterior m5 m7) (anterior m5 m8) (anterior m5 m9) (anterior m5 m10) (anterior m5 m11)
(anterior m5 m12) (anterior m6 m7) (anterior m6 m8) (anterior m6 m9) (anterior m6 m10) (anterior m6 m11) (anterior m6 m12)
(anterior m7 m8) (anterior m7 m9) (anterior m7 m10) (anterior m7 m11) (anterior m7 m12) (anterior m8 m9) (anterior m8 m10) (anterior m8 m11) (anterior m8 m12)
(anterior m9 m10) (anterior m9 m11) (anterior m9 m12) (anterior m10 m11) (anterior m10 m12) (anterior m11 m12)
)
(:goal (forall (?l - Libro) (imply (libro_a_leer ?l) (libro_asignado ?l)))))
