(define (problem libros)
(:domain libros)
(:objects m1 m2 m3 m4 m5 m6 m6 m7 m8 m9 m10 m11 m12 - Mes
adipiscing_elit vivamus_in_felis erat_nulla_tempus volutpat_sapien enim_lorem maecenas_leo_odio ultrices_posuere_cubilia libero_ut_massa elit aenean sed a_ipsum_integer proin_at_turpis fermentum_donec molestie_lorem_quisque at_turpis_a curabitur_in_libero eu_tincidunt_in amet dapibus_dolor curae metus iaculis_congue_vivamus venenatis consequat_metus_sapien neque_sapien morbi nec dolor_vel_est odio_donec_vitae rutrum_neque_aenean phasellus_id dui_luctus_rutrum massa_id_nisl blandit donec_ut vitae interdum pede_ac orci_luctus orci_nullam_molestie consectetuer_eget_rutrum hac_habitasse ut_dolor egestas nam_congue_risus nisi_volutpat_eleifend ante_ipsum_primis at_nibh_in sed justo_pellentesque aliquet_massa_id eros ultrices felis_eu_sapien nulla nam_dui massa_quis bibendum in_eleifend felis_donec_semper ipsum_primis ante_ipsum_primis amet_cursus mauris_lacinia_sapien gravida_sem turpis arcu ut_suscipit_a vestibulum nisi_at diam_cras_pellentesque maecenas_tincidunt_lacus dictumst orci_luctus_et congue integer sem_sed curae_donec urna_1 urna_2 urna_3 urna_4 urna_5 urna_6 urna_7 dui_1 dui_2 dui_3 dui_4 dui_5 dui_6 arcu_1 arcu_2 arcu_3 arcu_4 volutpat_convallis_1 volutpat_convallis_2 nulla_integer_1 nulla_integer_2 nulla_integer_3 nulla_integer_4 nulla_integer_5 nulla_integer_6 elit_proin_1 elit_proin_2 elit_proin_3 elit_proin_4 elit_proin_5 magnis_dis_parturient_1 magnis_dis_parturient_2 magnis_dis_parturient_3 magnis_dis_parturient_4 magnis_dis_parturient_5 consequat_lectus_1 consequat_lectus_2 consequat_lectus_3 consequat_lectus_4 interdum_1 interdum_2 interdum_3 interdum_4 interdum_5 interdum_6 vivamus_1 vivamus_2 vivamus_3 vivamus_4 vivamus_5 vivamus_6 leo_pellentesque_1 leo_pellentesque_2 leo_pellentesque_3 leo_pellentesque_4 leo_pellentesque_5 - Libro
)
(:init
(paralelo consectetuer_eget_rutrum vestibulum)
(paralelo vivamus_5 nulla_integer_5)
(paralelo proin_at_turpis ante_ipsum_primis)
(predecesor urna_1 urna_2)
(predecesor urna_2 urna_3)
(predecesor urna_3 urna_4)
(predecesor urna_4 urna_5)
(predecesor urna_5 urna_6)
(predecesor urna_6 urna_7)
(predecesor dui_1 dui_2)
(predecesor dui_2 dui_3)
(predecesor dui_3 dui_4)
(predecesor dui_4 dui_5)
(predecesor dui_5 dui_6)
(predecesor arcu_1 arcu_2)
(predecesor arcu_2 arcu_3)
(predecesor arcu_3 arcu_4)
(predecesor volutpat_convallis_1 volutpat_convallis_2)
(predecesor nulla_integer_1 nulla_integer_2)
(predecesor nulla_integer_2 nulla_integer_3)
(predecesor nulla_integer_3 nulla_integer_4)
(predecesor nulla_integer_4 nulla_integer_5)
(predecesor nulla_integer_5 nulla_integer_6)
(predecesor elit_proin_1 elit_proin_2)
(predecesor elit_proin_2 elit_proin_3)
(predecesor elit_proin_3 elit_proin_4)
(predecesor elit_proin_4 elit_proin_5)
(predecesor magnis_dis_parturient_1 magnis_dis_parturient_2)
(predecesor magnis_dis_parturient_2 magnis_dis_parturient_3)
(predecesor magnis_dis_parturient_3 magnis_dis_parturient_4)
(predecesor magnis_dis_parturient_4 magnis_dis_parturient_5)
(predecesor consequat_lectus_1 consequat_lectus_2)
(predecesor consequat_lectus_2 consequat_lectus_3)
(predecesor consequat_lectus_3 consequat_lectus_4)
(predecesor interdum_1 interdum_2)
(predecesor interdum_2 interdum_3)
(predecesor interdum_3 interdum_4)
(predecesor interdum_4 interdum_5)
(predecesor interdum_5 interdum_6)
(predecesor vivamus_1 vivamus_2)
(predecesor vivamus_2 vivamus_3)
(predecesor vivamus_3 vivamus_4)
(predecesor vivamus_4 vivamus_5)
(predecesor vivamus_5 vivamus_6)
(predecesor leo_pellentesque_1 leo_pellentesque_2)
(predecesor leo_pellentesque_2 leo_pellentesque_3)
(predecesor leo_pellentesque_3 leo_pellentesque_4)
(predecesor leo_pellentesque_4 leo_pellentesque_5)
(libro_leido dapibus_dolor)
(libro_leido volutpat_sapien)
(libro_leido ut_suscipit_a)
(libro_leido enim_lorem)
(libro_leido ultrices)
(libro_leido aliquet_massa_id)
(libro_leido erat_nulla_tempus)
(libro_leido felis_eu_sapien)
(libro_leido nam_dui)
(libro_leido sed)
(libro_leido curabitur_in_libero)
(libro_leido libero_ut_massa)
(libro_leido nam_congue_risus)
(libro_leido eu_tincidunt_in)
(libro_leido interdum)
(libro_leido amet_cursus)
(libro_leido ultrices_posuere_cubilia)
(libro_leido dui_luctus_rutrum)
(libro_leido consectetuer_eget_rutrum)
(libro_leido ut_dolor)
(libro_leido vitae)
(libro_leido metus)
(libro_leido felis_donec_semper)
(libro_leido congue)
(libro_leido justo_pellentesque)
(libro_leido nulla)
(libro_leido morbi)
(libro_leido vivamus_in_felis)
(libro_leido amet)
(libro_leido aenean)
(libro_leido dictumst)
(libro_leido donec_ut)
(libro_leido nisi_at)
(libro_leido molestie_lorem_quisque)
(libro_leido iaculis_congue_vivamus)
(libro_leido ipsum_primis)
(libro_leido orci_nullam_molestie)
(libro_leido dolor_vel_est)
(libro_leido sem_sed)
(libro_leido pede_ac)
(libro_a_leer vestibulum)
(libro_a_leer urna_7)
(libro_a_leer nulla_integer_6)
(libro_a_leer arcu_2)
(libro_a_leer interdum_2)
(libro_a_leer interdum_1)
(libro_a_leer interdum_5)
(libro_a_leer elit_proin_5)
(libro_a_leer arcu_4)
(libro_a_leer venenatis)
(libro_a_leer orci_luctus)
(libro_a_leer nisi_volutpat_eleifend)
(libro_a_leer magnis_dis_parturient_1)
(anterior m1 m2) (anterior m1 m3) (anterior m1 m4) (anterior m1 m5) (anterior m1 m6) (anterior m1 m7)
(anterior m1 m8) (anterior m1 m9) (anterior m1 m10) (anterior m1 m11) (anterior m1 m12)
(anterior m2 m3) (anterior m2 m4) (anterior m2 m5) (anterior m2 m6) (anterior m2 m7) (anterior m2 m8)
(anterior m2 m9) (anterior m2 m10) (anterior m2 m11) (anterior m2 m12)
(anterior m3 m4) (anterior m3 m5) (anterior m3 m6) (anterior m3 m7) (anterior m3 m8) (anterior m3 m9)
(anterior m3 m10) (anterior m3 m11) (anterior m3 m12)
(anterior m4 m5) (anterior m4 m6) (anterior m4 m7) (anterior m4 m8) (anterior m4 m9) (anterior m4 m10)
(anterior m4 m11) (anterior m4 m12) (anterior m5 m6) (anterior m5 m7) (anterior m5 m8) (anterior m5 m9) (anterior m5 m10) (anterior m5 m11)
(anterior m5 m12) (anterior m6 m7) (anterior m6 m8) (anterior m6 m9) (anterior m6 m10) (anterior m6 m11) (anterior m6 m12)
(anterior m7 m8) (anterior m7 m9) (anterior m7 m10) (anterior m7 m11) (anterior m7 m12) (anterior m8 m9) (anterior m8 m10) (anterior m8 m11) (anterior m8 m12)
(anterior m9 m10) (anterior m9 m11) (anterior m9 m12) (anterior m10 m11) (anterior m10 m12) (anterior m11 m12)
)
(:goal (forall (?l - Libro) (imply (libro_a_leer ?l) (libro_asignado ?l)))))
