(define (problem libros)
(:domain libros)
(:objects m1 m2 m3 m4 m5 m6 m6 m7 m8 m9 m10 m11 m12 - Mes
eget enim_lorem diam semper_interdum_mauris quis in_quis_justo ultrices_posuere luctus imperdiet_sapien_urna vestibulum in_eleifend_quam phasellus_sit_amet nisl_venenatis nisi curabitur_in_libero vestibulum dolor_vel_est venenatis_tristique lacus nisl_nunc maecenas cubilia luctus_nec felis_ut_at luctus_et eget_tempus_vel integer in quisque_porta donec_ut_dolor turpis_eget rutrum_neque_1 rutrum_neque_2 rutrum_neque_3 rutrum_neque_4 rutrum_neque_5 rutrum_neque_6 rutrum_neque_7 maecenas_1 maecenas_2 amet_cursus_1 amet_cursus_2 amet_cursus_3 amet_cursus_4 amet_cursus_5 amet_cursus_6 nam_dui_1 nam_dui_2 nam_dui_3 eros_vestibulum_1 eros_vestibulum_2 eros_vestibulum_3 eros_vestibulum_4 donec_dapibus_1 donec_dapibus_2 donec_dapibus_3 donec_dapibus_4 donec_dapibus_5 dictumst_1 dictumst_2 id_massa_id_1 id_massa_id_2 id_massa_id_3 id_massa_id_4 id_massa_id_5 id_massa_id_6 et_1 et_2 et_3 et_4 et_5 - Libro
)
(:init
(predecesor rutrum_neque_1 rutrum_neque_2)
(predecesor rutrum_neque_2 rutrum_neque_3)
(predecesor rutrum_neque_3 rutrum_neque_4)
(predecesor rutrum_neque_4 rutrum_neque_5)
(predecesor rutrum_neque_5 rutrum_neque_6)
(predecesor rutrum_neque_6 rutrum_neque_7)
(predecesor maecenas_1 maecenas_2)
(predecesor amet_cursus_1 amet_cursus_2)
(predecesor amet_cursus_2 amet_cursus_3)
(predecesor amet_cursus_3 amet_cursus_4)
(predecesor amet_cursus_4 amet_cursus_5)
(predecesor amet_cursus_5 amet_cursus_6)
(predecesor nam_dui_1 nam_dui_2)
(predecesor nam_dui_2 nam_dui_3)
(predecesor eros_vestibulum_1 eros_vestibulum_2)
(predecesor eros_vestibulum_2 eros_vestibulum_3)
(predecesor eros_vestibulum_3 eros_vestibulum_4)
(predecesor donec_dapibus_1 donec_dapibus_2)
(predecesor donec_dapibus_2 donec_dapibus_3)
(predecesor donec_dapibus_3 donec_dapibus_4)
(predecesor donec_dapibus_4 donec_dapibus_5)
(predecesor dictumst_1 dictumst_2)
(predecesor id_massa_id_1 id_massa_id_2)
(predecesor id_massa_id_2 id_massa_id_3)
(predecesor id_massa_id_3 id_massa_id_4)
(predecesor id_massa_id_4 id_massa_id_5)
(predecesor id_massa_id_5 id_massa_id_6)
(predecesor et_1 et_2)
(predecesor et_2 et_3)
(predecesor et_3 et_4)
(predecesor et_4 et_5)
(libro_a_leer diam)
(libro_a_leer amet_cursus_4)
(libro_a_leer maecenas_2)
(libro_a_leer turpis_eget)
(libro_a_leer rutrum_neque_3)
(libro_a_leer amet_cursus_3)
(libro_a_leer amet_cursus_2)
(libro_a_leer id_massa_id_4)
(libro_a_leer rutrum_neque_6)
(libro_a_leer donec_dapibus_1)
(libro_a_leer donec_dapibus_4)
(anterior m1 m2) (anterior m1 m3) (anterior m1 m4) (anterior m1 m5) (anterior m1 m6) (anterior m1 m7)
(anterior m1 m8) (anterior m1 m9) (anterior m1 m10) (anterior m1 m11) (anterior m1 m12)
(anterior m2 m3) (anterior m2 m4) (anterior m2 m5) (anterior m2 m6) (anterior m2 m7) (anterior m2 m8)
(anterior m2 m9) (anterior m2 m10) (anterior m2 m11) (anterior m2 m12)
(anterior m3 m4) (anterior m3 m5) (anterior m3 m6) (anterior m3 m7) (anterior m3 m8) (anterior m3 m9)
(anterior m3 m10) (anterior m3 m11) (anterior m3 m12)
(anterior m4 m5) (anterior m4 m6) (anterior m4 m7) (anterior m4 m8) (anterior m4 m9) (anterior m4 m10)
(anterior m4 m11) (anterior m4 m12) (anterior m5 m6) (anterior m5 m7) (anterior m5 m8) (anterior m5 m9) (anterior m5 m10) (anterior m5 m11)
(anterior m5 m12) (anterior m6 m7) (anterior m6 m8) (anterior m6 m9) (anterior m6 m10) (anterior m6 m11) (anterior m6 m12)
(anterior m7 m8) (anterior m7 m9) (anterior m7 m10) (anterior m7 m11) (anterior m7 m12) (anterior m8 m9) (anterior m8 m10) (anterior m8 m11) (anterior m8 m12)
(anterior m9 m10) (anterior m9 m11) (anterior m9 m12) (anterior m10 m11) (anterior m10 m12) (anterior m11 m12)
)
(:goal (forall (?l - Libro) (imply (libro_a_leer ?l) (libro_asignado ?l)))))
